(() => {
  const languages = [
    ['en','English'],['fr','Français'],['de','Deutsch'],['es','Español'],['it','Italiano'],
    ['nl','Nederlands'],['pl','Polski'],['pt','Português'],['ro','Română'],['uk','Українська'],
    ['cs','Čeština'],['sk','Slovenčina'],['hu','Magyar'],['el','Ελληνικά'],['tr','Türkçe'],
    ['sv','Svenska'],['no','Norsk'],['da','Dansk'],['fi','Suomi'],['et','Eesti'],
    ['lv','Latviešu'],['lt','Lietuvių'],['hr','Hrvatski'],['sl','Slovenščina'],['bg','Български'],
    ['ru','Русский'],['ar','العربية'],['he','עברית'],['hi','हिन्दी'],['bn','বাংলা'],
    ['ur','اردو'],['zh-CN','简体中文'],['zh-TW','繁體中文'],['ja','日本語'],['ko','한국어'],
    ['th','ไทย'],['vi','Tiếng Việt'],['id','Bahasa Indonesia'],['ms','Bahasa Melayu'],['fil','Filipino']
  ];
  const rtlLanguages = new Set(['ar','he','ur']);
  const en = {
    language:'Language', choose_language:'CHOOSE LANGUAGE', choose_your_language:'Choose your language', currency_note:'All prices remain in pounds sterling (£).',
    browse_heading:'How would you like to browse?', browse_intro:'Start immediately without giving us any details, or save your visit so you can return later and continue where you left off.', just_browsing:"I'm just browsing", just_browsing_desc:'No personal information is needed. This iPad clears automatically after inactivity.', save_visit:'Save my visit', save_visit_desc:'Use your email to save favourites, basket and browsing progress for this event.', continue_saved:'Already saved a visit? Continue here', your_privacy:'Your privacy', privacy_one:'No personal information is stored unless you choose to save your visit. Saving a visit does not sign you up for future-event messages.', privacy_two:"You can separately opt in if you would like Sophie's Photography to keep your details for future events.", save_my_visit_caps:'SAVE MY VISIT', return_when_needed:'Return whenever you need to', email_use:'Your email is used to save this event visit, including favourites, basket and where you were browsing.', email_address:'Email address', marketing_opt_in:"Keep my details so Sophie's Photography can contact me about future events and offers.", opt_in_optional:'This optional box is unticked by default. You can save your visit without opting in.', save_and_browse:'Save and start browsing', continue_visit_caps:'CONTINUE MY VISIT', welcome_back:'Welcome back', enter_saved_email:'Enter the email address used to save your visit.', continue_visit:'Continue my visit',
    live_gallery:'LIVE EVENT GALLERY', gallery_intro:'Choose a folder to open its gallery, or search using the dancer number visible on the dancer.', search_event:'Search this event', search_placeholder:'For example: dancer 124', search:'Search', reopen_favourites:'Reopen my favourites', basket_checkout:'View basket & checkout', automatic_number_search:'Automatic dancer-number search', number_search_note:'Numbers are read automatically from photographs and may occasionally be missed or misread. Browse the event folders as well, because there may be additional photographs of the dancer.', event_folders:'Event folders', browse_caps:'BROWSE', gallery_caps:'GALLERY', save_favourite:'Save favourite', add:'Add', add_to_basket:'Add photograph to basket', end_session:'End my session',
    shop_checkout:'SHOP & CHECKOUT', your_basket:'Your basket', basket_intro:'Choose a product for each photograph. Use “Add another product” when you want the same photograph as a print, keyring, download or another item. Multibuy savings are applied automatically.', quick_checkout:'Quick checkout', view_all_products:'View all products', basket_empty:'Your basket is empty. Return to the gallery and add photographs first.', name:'Name', email:'Email', payment_method:'Payment method', pay_at_stand:'Pay at the stand with SumUp', pay_online:'Pay online with SumUp', total:'Total', place_order:'Place order',
    my_favourites_caps:'MY FAVOURITES', saved_photos:'Your saved photographs', return_previous:'Return to previous screen', add_all_checkout:'Add all to basket & checkout', open_favourites:'Open my favourites', no_favourites:'No favourites yet', no_favourites_desc:'Return to the event and tap the heart on photographs you would like to keep.', find_photos:'Find photographs', private_event:'PRIVATE EVENT', enter_access_code:'Enter the event access code to view the photographs.', access_code:'Access code', open_gallery:'Open gallery'
  };
  const T = {
    en,
    fr:{language:'Langue',choose_language:'CHOISIR LA LANGUE',choose_your_language:'Choisissez votre langue',currency_note:'Tous les prix restent en livres sterling (£).',browse_heading:'Comment souhaitez-vous parcourir les photos ?',browse_intro:'Commencez sans fournir de renseignements, ou enregistrez votre visite pour revenir plus tard.',just_browsing:'Je regarde simplement',just_browsing_desc:"Aucune information personnelle n’est nécessaire. Cet iPad s’efface automatiquement après une période d’inactivité.",save_visit:'Enregistrer ma visite',save_visit_desc:'Utilisez votre e-mail pour enregistrer vos favoris, votre panier et votre progression.',continue_saved:'Visite déjà enregistrée ? Continuer ici',your_privacy:'Votre vie privée',privacy_one:"Aucune information personnelle n’est stockée sauf si vous choisissez d’enregistrer votre visite.",privacy_two:'Vous pouvez accepter séparément que vos coordonnées soient conservées pour de futurs événements.',email_address:'Adresse e-mail',save_and_browse:'Enregistrer et commencer',continue_visit:'Continuer ma visite',welcome_back:'Bon retour',search_event:'Rechercher dans cet événement',search:'Rechercher',reopen_favourites:'Rouvrir mes favoris',basket_checkout:'Voir le panier et payer',event_folders:'Dossiers de l’événement',add:'Ajouter',end_session:'Terminer ma session',your_basket:'Votre panier',quick_checkout:'Paiement rapide',view_all_products:'Voir tous les produits',basket_empty:'Votre panier est vide.',name:'Nom',email:'E-mail',payment_method:'Mode de paiement',total:'Total',place_order:'Passer la commande',saved_photos:'Vos photos enregistrées',open_favourites:'Ouvrir mes favoris',find_photos:'Trouver des photos',access_code:'Code d’accès',open_gallery:'Ouvrir la galerie'},
    de:{language:'Sprache',choose_language:'SPRACHE WÄHLEN',choose_your_language:'Wählen Sie Ihre Sprache',currency_note:'Alle Preise bleiben in Pfund Sterling (£).',browse_heading:'Wie möchten Sie stöbern?',just_browsing:'Ich schaue mich nur um',just_browsing_desc:'Es sind keine persönlichen Angaben erforderlich. Dieses iPad wird nach Inaktivität automatisch zurückgesetzt.',save_visit:'Meinen Besuch speichern',continue_saved:'Besuch bereits gespeichert? Hier fortfahren',your_privacy:'Ihre Privatsphäre',email_address:'E-Mail-Adresse',save_and_browse:'Speichern und stöbern',continue_visit:'Besuch fortsetzen',welcome_back:'Willkommen zurück',search_event:'Diese Veranstaltung durchsuchen',search:'Suchen',reopen_favourites:'Meine Favoriten öffnen',basket_checkout:'Warenkorb ansehen & bezahlen',event_folders:'Veranstaltungsordner',add:'Hinzufügen',end_session:'Sitzung beenden',your_basket:'Ihr Warenkorb',quick_checkout:'Schnell bezahlen',view_all_products:'Alle Produkte anzeigen',basket_empty:'Ihr Warenkorb ist leer.',name:'Name',email:'E-Mail',payment_method:'Zahlungsart',total:'Gesamt',place_order:'Bestellung aufgeben',saved_photos:'Ihre gespeicherten Fotos',open_favourites:'Favoriten öffnen',find_photos:'Fotos finden',access_code:'Zugangscode',open_gallery:'Galerie öffnen'},
    es:{language:'Idioma',choose_language:'ELEGIR IDIOMA',choose_your_language:'Elige tu idioma',currency_note:'Todos los precios se mantienen en libras esterlinas (£).',browse_heading:'¿Cómo quieres explorar?',just_browsing:'Solo estoy mirando',just_browsing_desc:'No se necesita información personal. Este iPad se borra automáticamente tras un periodo de inactividad.',save_visit:'Guardar mi visita',continue_saved:'¿Ya guardaste una visita? Continúa aquí',your_privacy:'Tu privacidad',email_address:'Correo electrónico',save_and_browse:'Guardar y empezar',continue_visit:'Continuar mi visita',welcome_back:'Bienvenido de nuevo',search_event:'Buscar en este evento',search:'Buscar',reopen_favourites:'Abrir mis favoritos',basket_checkout:'Ver cesta y pagar',event_folders:'Carpetas del evento',add:'Añadir',end_session:'Finalizar mi sesión',your_basket:'Tu cesta',quick_checkout:'Pago rápido',view_all_products:'Ver todos los productos',basket_empty:'Tu cesta está vacía.',name:'Nombre',email:'Correo electrónico',payment_method:'Método de pago',total:'Total',place_order:'Realizar pedido',saved_photos:'Tus fotografías guardadas',open_favourites:'Abrir mis favoritos',find_photos:'Buscar fotografías',access_code:'Código de acceso',open_gallery:'Abrir galería'},
    it:{language:'Lingua',choose_language:'SCEGLI LA LINGUA',choose_your_language:'Scegli la tua lingua',currency_note:'Tutti i prezzi restano in sterline (£).',browse_heading:'Come vuoi sfogliare?',just_browsing:'Sto solo guardando',save_visit:'Salva la mia visita',continue_saved:'Hai già salvato una visita? Continua qui',your_privacy:'La tua privacy',email_address:'Indirizzo e-mail',save_and_browse:'Salva e inizia',continue_visit:'Continua la mia visita',welcome_back:'Bentornato',search_event:'Cerca in questo evento',search:'Cerca',reopen_favourites:'Riapri i miei preferiti',basket_checkout:'Vedi carrello e paga',event_folders:'Cartelle evento',add:'Aggiungi',end_session:'Termina sessione',your_basket:'Il tuo carrello',quick_checkout:'Pagamento rapido',view_all_products:'Vedi tutti i prodotti',basket_empty:'Il carrello è vuoto.',name:'Nome',email:'E-mail',payment_method:'Metodo di pagamento',total:'Totale',place_order:'Invia ordine',saved_photos:'Le tue foto salvate',open_favourites:'Apri i preferiti',find_photos:'Trova fotografie',access_code:'Codice di accesso',open_gallery:'Apri galleria'},
    nl:{language:'Taal',choose_language:'KIES TAAL',choose_your_language:'Kies uw taal',currency_note:'Alle prijzen blijven in Britse ponden (£).',browse_heading:'Hoe wilt u bladeren?',just_browsing:'Ik kijk alleen rond',save_visit:'Mijn bezoek opslaan',continue_saved:'Bezoek al opgeslagen? Ga hier verder',your_privacy:'Uw privacy',email_address:'E-mailadres',save_and_browse:'Opslaan en bladeren',continue_visit:'Mijn bezoek voortzetten',welcome_back:'Welkom terug',search_event:'Zoek in dit evenement',search:'Zoeken',reopen_favourites:'Mijn favorieten openen',basket_checkout:'Mandje bekijken en afrekenen',event_folders:'Evenementmappen',add:'Toevoegen',end_session:'Sessie beëindigen',your_basket:'Uw mandje',quick_checkout:'Snel afrekenen',view_all_products:'Alle producten bekijken',basket_empty:'Uw mandje is leeg.',name:'Naam',email:'E-mail',payment_method:'Betaalmethode',total:'Totaal',place_order:'Bestelling plaatsen',saved_photos:'Uw opgeslagen foto’s',open_favourites:'Favorieten openen',find_photos:'Foto’s zoeken',access_code:'Toegangscode',open_gallery:'Galerij openen'},
    pl:{language:'Język',choose_language:'WYBIERZ JĘZYK',choose_your_language:'Wybierz język',currency_note:'Wszystkie ceny pozostają w funtach szterlingach (£).',browse_heading:'Jak chcesz przeglądać?',just_browsing:'Tylko przeglądam',save_visit:'Zapisz moją wizytę',continue_saved:'Masz zapisaną wizytę? Kontynuuj tutaj',your_privacy:'Twoja prywatność',email_address:'Adres e-mail',save_and_browse:'Zapisz i rozpocznij',continue_visit:'Kontynuuj wizytę',welcome_back:'Witamy ponownie',search_event:'Przeszukaj wydarzenie',search:'Szukaj',reopen_favourites:'Otwórz ulubione',basket_checkout:'Zobacz koszyk i zapłać',event_folders:'Foldery wydarzenia',add:'Dodaj',end_session:'Zakończ sesję',your_basket:'Twój koszyk',quick_checkout:'Szybka płatność',view_all_products:'Zobacz wszystkie produkty',basket_empty:'Twój koszyk jest pusty.',name:'Imię i nazwisko',email:'E-mail',payment_method:'Metoda płatności',total:'Razem',place_order:'Złóż zamówienie',saved_photos:'Zapisane zdjęcia',open_favourites:'Otwórz ulubione',find_photos:'Znajdź zdjęcia',access_code:'Kod dostępu',open_gallery:'Otwórz galerię'},
    pt:{language:'Idioma',choose_language:'ESCOLHER IDIOMA',choose_your_language:'Escolha o seu idioma',currency_note:'Todos os preços permanecem em libras esterlinas (£).',browse_heading:'Como pretende navegar?',just_browsing:'Estou apenas a ver',save_visit:'Guardar a minha visita',continue_saved:'Já guardou uma visita? Continue aqui',your_privacy:'A sua privacidade',email_address:'Endereço de e-mail',save_and_browse:'Guardar e começar',continue_visit:'Continuar a minha visita',welcome_back:'Bem-vindo de volta',search_event:'Pesquisar neste evento',search:'Pesquisar',reopen_favourites:'Abrir favoritos',basket_checkout:'Ver cesto e pagar',event_folders:'Pastas do evento',add:'Adicionar',end_session:'Terminar sessão',your_basket:'O seu cesto',quick_checkout:'Pagamento rápido',view_all_products:'Ver todos os produtos',basket_empty:'O seu cesto está vazio.',name:'Nome',email:'E-mail',payment_method:'Método de pagamento',total:'Total',place_order:'Fazer pedido',saved_photos:'As suas fotografias guardadas',open_favourites:'Abrir favoritos',find_photos:'Encontrar fotografias',access_code:'Código de acesso',open_gallery:'Abrir galeria'},
    ro:{language:'Limbă',choose_language:'ALEGEȚI LIMBA',choose_your_language:'Alegeți limba',currency_note:'Toate prețurile rămân în lire sterline (£).',browse_heading:'Cum doriți să răsfoiți?',just_browsing:'Doar răsfoiesc',save_visit:'Salvează vizita',continue_saved:'Ați salvat deja o vizită? Continuați aici',your_privacy:'Confidențialitatea dvs.',email_address:'Adresă de e-mail',save_and_browse:'Salvează și începe',continue_visit:'Continuă vizita',welcome_back:'Bine ați revenit',search_event:'Caută în acest eveniment',search:'Caută',reopen_favourites:'Deschide favoritele',basket_checkout:'Vezi coșul și plătește',event_folders:'Dosarele evenimentului',add:'Adaugă',end_session:'Încheie sesiunea',your_basket:'Coșul dvs.',quick_checkout:'Plată rapidă',view_all_products:'Vezi toate produsele',basket_empty:'Coșul este gol.',name:'Nume',email:'E-mail',payment_method:'Metodă de plată',total:'Total',place_order:'Plasează comanda',saved_photos:'Fotografiile salvate',open_favourites:'Deschide favoritele',find_photos:'Găsește fotografii',access_code:'Cod de acces',open_gallery:'Deschide galeria'},
    uk:{language:'Мова',choose_language:'ОБЕРІТЬ МОВУ',choose_your_language:'Оберіть мову',currency_note:'Усі ціни залишаються у фунтах стерлінгів (£).',browse_heading:'Як ви хочете переглядати?',just_browsing:'Я лише переглядаю',save_visit:'Зберегти мій візит',continue_saved:'Візит уже збережено? Продовжити тут',your_privacy:'Ваша конфіденційність',email_address:'Електронна адреса',save_and_browse:'Зберегти й почати',continue_visit:'Продовжити візит',welcome_back:'З поверненням',search_event:'Пошук у цій події',search:'Пошук',reopen_favourites:'Відкрити обране',basket_checkout:'Переглянути кошик і оплатити',event_folders:'Папки події',add:'Додати',end_session:'Завершити сеанс',your_basket:'Ваш кошик',quick_checkout:'Швидке оформлення',view_all_products:'Переглянути всі товари',basket_empty:'Ваш кошик порожній.',name:'Ім’я',email:'Електронна пошта',payment_method:'Спосіб оплати',total:'Разом',place_order:'Оформити замовлення',saved_photos:'Ваші збережені фотографії',open_favourites:'Відкрити обране',find_photos:'Знайти фотографії',access_code:'Код доступу',open_gallery:'Відкрити галерею'}
  };
  Object.assign(T, {
    cs:{language:'Jazyk',choose_language:'VYBERTE JAZYK',choose_your_language:'Vyberte si jazyk',currency_note:'Všechny ceny zůstávají v librách šterlinků (£).',browse_heading:'Jak chcete procházet?',just_browsing:'Jen se dívám',save_visit:'Uložit návštěvu',continue_saved:'Máte uloženou návštěvu? Pokračujte zde',your_privacy:'Vaše soukromí',email_address:'E-mailová adresa',save_and_browse:'Uložit a začít',continue_visit:'Pokračovat v návštěvě',search_event:'Hledat v této události',search:'Hledat',reopen_favourites:'Otevřít oblíbené',basket_checkout:'Košík a platba',event_folders:'Složky události',end_session:'Ukončit relaci',your_basket:'Váš košík',total:'Celkem',place_order:'Odeslat objednávku'},
    sk:{language:'Jazyk',choose_language:'VYBERTE JAZYK',choose_your_language:'Vyberte si jazyk',currency_note:'Všetky ceny zostávajú v librách šterlingov (£).',browse_heading:'Ako chcete prehliadať?',just_browsing:'Len si prezerám',save_visit:'Uložiť návštevu',continue_saved:'Máte uloženú návštevu? Pokračujte tu',your_privacy:'Vaše súkromie',email_address:'E-mailová adresa',save_and_browse:'Uložiť a začať',continue_visit:'Pokračovať v návšteve',search_event:'Hľadať v tomto podujatí',search:'Hľadať',reopen_favourites:'Otvoriť obľúbené',basket_checkout:'Košík a platba',event_folders:'Priečinky podujatia',end_session:'Ukončiť reláciu',your_basket:'Váš košík',total:'Spolu',place_order:'Odoslať objednávku'},
    hu:{language:'Nyelv',choose_language:'NYELV KIVÁLASZTÁSA',choose_your_language:'Válasszon nyelvet',currency_note:'Minden ár angol fontban (£) marad.',browse_heading:'Hogyan szeretne böngészni?',just_browsing:'Csak böngészek',save_visit:'Látogatás mentése',continue_saved:'Már mentett látogatást? Folytatás itt',your_privacy:'Adatvédelem',email_address:'E-mail-cím',save_and_browse:'Mentés és böngészés',continue_visit:'Látogatás folytatása',search_event:'Keresés az eseményben',search:'Keresés',reopen_favourites:'Kedvencek megnyitása',basket_checkout:'Kosár és fizetés',event_folders:'Eseménymappák',end_session:'Munkamenet befejezése',your_basket:'Az Ön kosara',total:'Összesen',place_order:'Megrendelés leadása'},
    el:{language:'Γλώσσα',choose_language:'ΕΠΙΛΟΓΗ ΓΛΩΣΣΑΣ',choose_your_language:'Επιλέξτε τη γλώσσα σας',currency_note:'Όλες οι τιμές παραμένουν σε λίρες στερλίνες (£).',browse_heading:'Πώς θέλετε να περιηγηθείτε;',just_browsing:'Απλώς περιηγούμαι',save_visit:'Αποθήκευση επίσκεψης',continue_saved:'Έχετε αποθηκευμένη επίσκεψη; Συνεχίστε εδώ',your_privacy:'Το απόρρητό σας',email_address:'Διεύθυνση email',save_and_browse:'Αποθήκευση και έναρξη',continue_visit:'Συνέχιση επίσκεψης',search_event:'Αναζήτηση στην εκδήλωση',search:'Αναζήτηση',reopen_favourites:'Άνοιγμα αγαπημένων',basket_checkout:'Καλάθι και πληρωμή',event_folders:'Φάκελοι εκδήλωσης',end_session:'Τερματισμός συνεδρίας',your_basket:'Το καλάθι σας',total:'Σύνολο',place_order:'Υποβολή παραγγελίας'},
    tr:{language:'Dil',choose_language:'DİL SEÇİN',choose_your_language:'Dilinizi seçin',currency_note:'Tüm fiyatlar İngiliz sterlini (£) olarak kalır.',browse_heading:'Nasıl göz atmak istersiniz?',just_browsing:'Sadece göz atıyorum',save_visit:'Ziyaretimi kaydet',continue_saved:'Kayıtlı ziyaretiniz var mı? Buradan devam edin',your_privacy:'Gizliliğiniz',email_address:'E-posta adresi',save_and_browse:'Kaydet ve göz at',continue_visit:'Ziyaretime devam et',search_event:'Bu etkinlikte ara',search:'Ara',reopen_favourites:'Favorilerimi aç',basket_checkout:'Sepet ve ödeme',event_folders:'Etkinlik klasörleri',end_session:'Oturumu bitir',your_basket:'Sepetiniz',total:'Toplam',place_order:'Sipariş ver'},
    sv:{language:'Språk',choose_language:'VÄLJ SPRÅK',choose_your_language:'Välj ditt språk',currency_note:'Alla priser visas fortfarande i brittiska pund (£).',browse_heading:'Hur vill du bläddra?',just_browsing:'Jag tittar bara',save_visit:'Spara mitt besök',continue_saved:'Har du sparat ett besök? Fortsätt här',your_privacy:'Din integritet',email_address:'E-postadress',save_and_browse:'Spara och börja',continue_visit:'Fortsätt mitt besök',search_event:'Sök i evenemanget',search:'Sök',reopen_favourites:'Öppna favoriter',basket_checkout:'Varukorg och betalning',event_folders:'Evenemangsmappar',end_session:'Avsluta session',your_basket:'Din varukorg',total:'Totalt',place_order:'Lägg beställning'},
    no:{language:'Språk',choose_language:'VELG SPRÅK',choose_your_language:'Velg språket ditt',currency_note:'Alle priser vises fortsatt i britiske pund (£).',browse_heading:'Hvordan vil du bla?',just_browsing:'Jeg bare ser',save_visit:'Lagre besøket mitt',continue_saved:'Har du lagret et besøk? Fortsett her',your_privacy:'Personvernet ditt',email_address:'E-postadresse',save_and_browse:'Lagre og start',continue_visit:'Fortsett besøket',search_event:'Søk i arrangementet',search:'Søk',reopen_favourites:'Åpne favoritter',basket_checkout:'Handlekurv og betaling',event_folders:'Arrangementsmapper',end_session:'Avslutt økt',your_basket:'Handlekurven din',total:'Totalt',place_order:'Send bestilling'},
    da:{language:'Sprog',choose_language:'VÆLG SPROG',choose_your_language:'Vælg dit sprog',currency_note:'Alle priser vises fortsat i britiske pund (£).',browse_heading:'Hvordan vil du gennemse?',just_browsing:'Jeg kigger bare',save_visit:'Gem mit besøg',continue_saved:'Har du gemt et besøg? Fortsæt her',your_privacy:'Dit privatliv',email_address:'E-mailadresse',save_and_browse:'Gem og start',continue_visit:'Fortsæt mit besøg',search_event:'Søg i arrangementet',search:'Søg',reopen_favourites:'Åbn favoritter',basket_checkout:'Kurv og betaling',event_folders:'Arrangementsmapper',end_session:'Afslut session',your_basket:'Din kurv',total:'I alt',place_order:'Afgiv ordre'},
    fi:{language:'Kieli',choose_language:'VALITSE KIELI',choose_your_language:'Valitse kielesi',currency_note:'Kaikki hinnat pysyvät Englannin puntina (£).',browse_heading:'Miten haluat selata?',just_browsing:'Selailen vain',save_visit:'Tallenna käyntini',continue_saved:'Onko käyntisi tallennettu? Jatka tästä',your_privacy:'Yksityisyytesi',email_address:'Sähköpostiosoite',save_and_browse:'Tallenna ja aloita',continue_visit:'Jatka käyntiä',search_event:'Hae tapahtumasta',search:'Hae',reopen_favourites:'Avaa suosikit',basket_checkout:'Ostoskori ja maksu',event_folders:'Tapahtumakansiot',end_session:'Lopeta istunto',your_basket:'Ostoskorisi',total:'Yhteensä',place_order:'Tee tilaus'},
    et:{language:'Keel',choose_language:'VALI KEEL',choose_your_language:'Valige keel',currency_note:'Kõik hinnad jäävad naelsterlingitesse (£).',browse_heading:'Kuidas soovite sirvida?',just_browsing:'Ma lihtsalt sirvin',save_visit:'Salvesta külastus',continue_saved:'Kas külastus on salvestatud? Jätkake siin',your_privacy:'Teie privaatsus',email_address:'E-posti aadress',save_and_browse:'Salvesta ja alusta',continue_visit:'Jätka külastust',search_event:'Otsi sündmusest',search:'Otsi',reopen_favourites:'Ava lemmikud',basket_checkout:'Ostukorv ja makse',event_folders:'Sündmuse kaustad',end_session:'Lõpeta seanss',your_basket:'Teie ostukorv',total:'Kokku',place_order:'Esita tellimus'},
    lv:{language:'Valoda',choose_language:'IZVĒLĒTIES VALODU',choose_your_language:'Izvēlieties valodu',currency_note:'Visas cenas paliek sterliņu mārciņās (£).',browse_heading:'Kā vēlaties pārlūkot?',just_browsing:'Es tikai pārlūkoju',save_visit:'Saglabāt apmeklējumu',continue_saved:'Vai apmeklējums ir saglabāts? Turpiniet šeit',your_privacy:'Jūsu privātums',email_address:'E-pasta adrese',save_and_browse:'Saglabāt un sākt',continue_visit:'Turpināt apmeklējumu',search_event:'Meklēt pasākumā',search:'Meklēt',reopen_favourites:'Atvērt izlasi',basket_checkout:'Grozs un apmaksa',event_folders:'Pasākuma mapes',end_session:'Beigt sesiju',your_basket:'Jūsu grozs',total:'Kopā',place_order:'Veikt pasūtījumu'},
    lt:{language:'Kalba',choose_language:'PASIRINKITE KALBĄ',choose_your_language:'Pasirinkite kalbą',currency_note:'Visos kainos lieka svarais sterlingų (£).',browse_heading:'Kaip norite naršyti?',just_browsing:'Tik naršau',save_visit:'Išsaugoti apsilankymą',continue_saved:'Turite išsaugotą apsilankymą? Tęskite čia',your_privacy:'Jūsų privatumas',email_address:'El. pašto adresas',save_and_browse:'Išsaugoti ir pradėti',continue_visit:'Tęsti apsilankymą',search_event:'Ieškoti renginyje',search:'Ieškoti',reopen_favourites:'Atverti mėgstamiausius',basket_checkout:'Krepšelis ir apmokėjimas',event_folders:'Renginio aplankai',end_session:'Baigti seansą',your_basket:'Jūsų krepšelis',total:'Iš viso',place_order:'Pateikti užsakymą'},
    hr:{language:'Jezik',choose_language:'ODABERITE JEZIK',choose_your_language:'Odaberite jezik',currency_note:'Sve cijene ostaju u britanskim funtama (£).',browse_heading:'Kako želite pregledavati?',just_browsing:'Samo pregledavam',save_visit:'Spremi moj posjet',continue_saved:'Već ste spremili posjet? Nastavite ovdje',your_privacy:'Vaša privatnost',email_address:'Adresa e-pošte',save_and_browse:'Spremi i započni',continue_visit:'Nastavi posjet',search_event:'Pretraži događaj',search:'Pretraži',reopen_favourites:'Otvori favorite',basket_checkout:'Košarica i plaćanje',event_folders:'Mape događaja',end_session:'Završi sesiju',your_basket:'Vaša košarica',total:'Ukupno',place_order:'Pošalji narudžbu'},
    sl:{language:'Jezik',choose_language:'IZBERITE JEZIK',choose_your_language:'Izberite jezik',currency_note:'Vse cene ostanejo v britanskih funtih (£).',browse_heading:'Kako želite brskati?',just_browsing:'Samo brskam',save_visit:'Shrani moj obisk',continue_saved:'Imate shranjen obisk? Nadaljujte tukaj',your_privacy:'Vaša zasebnost',email_address:'E-poštni naslov',save_and_browse:'Shrani in začni',continue_visit:'Nadaljuj obisk',search_event:'Išči v dogodku',search:'Išči',reopen_favourites:'Odpri priljubljene',basket_checkout:'Košarica in plačilo',event_folders:'Mape dogodka',end_session:'Končaj sejo',your_basket:'Vaša košarica',total:'Skupaj',place_order:'Oddaj naročilo'},
    bg:{language:'Език',choose_language:'ИЗБЕРЕТЕ ЕЗИК',choose_your_language:'Изберете език',currency_note:'Всички цени остават в британски лири (£).',browse_heading:'Как искате да разглеждате?',just_browsing:'Само разглеждам',save_visit:'Запази посещението ми',continue_saved:'Имате запазено посещение? Продължете тук',your_privacy:'Вашата поверителност',email_address:'Имейл адрес',save_and_browse:'Запази и започни',continue_visit:'Продължи посещението',search_event:'Търсене в събитието',search:'Търсене',reopen_favourites:'Отвори любими',basket_checkout:'Кошница и плащане',event_folders:'Папки на събитието',end_session:'Край на сесията',your_basket:'Вашата кошница',total:'Общо',place_order:'Направи поръчка'},
    ru:{language:'Язык',choose_language:'ВЫБЕРИТЕ ЯЗЫК',choose_your_language:'Выберите язык',currency_note:'Все цены остаются в фунтах стерлингов (£).',browse_heading:'Как вы хотите просматривать?',just_browsing:'Я просто смотрю',save_visit:'Сохранить мой визит',continue_saved:'Уже сохранили визит? Продолжите здесь',your_privacy:'Ваша конфиденциальность',email_address:'Адрес электронной почты',save_and_browse:'Сохранить и начать',continue_visit:'Продолжить визит',search_event:'Поиск по событию',search:'Поиск',reopen_favourites:'Открыть избранное',basket_checkout:'Корзина и оплата',event_folders:'Папки события',end_session:'Завершить сеанс',your_basket:'Ваша корзина',total:'Итого',place_order:'Оформить заказ'},
    ar:{language:'اللغة',choose_language:'اختر اللغة',choose_your_language:'اختر لغتك',currency_note:'تظل جميع الأسعار بالجنيه الإسترليني (£).',browse_heading:'كيف ترغب في التصفح؟',just_browsing:'أنا أتصفح فقط',save_visit:'حفظ زيارتي',continue_saved:'هل حفظت زيارة من قبل؟ تابع من هنا',your_privacy:'خصوصيتك',email_address:'عنوان البريد الإلكتروني',save_and_browse:'حفظ وبدء التصفح',continue_visit:'متابعة زيارتي',search_event:'البحث في هذه الفعالية',search:'بحث',reopen_favourites:'فتح المفضلة',basket_checkout:'السلة والدفع',event_folders:'مجلدات الفعالية',end_session:'إنهاء الجلسة',your_basket:'سلتك',total:'الإجمالي',place_order:'إرسال الطلب'},
    he:{language:'שפה',choose_language:'בחירת שפה',choose_your_language:'בחרו את השפה שלכם',currency_note:'כל המחירים נשארים בלירות שטרלינג (£).',browse_heading:'כיצד תרצו לגלוש?',just_browsing:'אני רק מסתכל/ת',save_visit:'שמירת הביקור שלי',continue_saved:'כבר שמרתם ביקור? המשיכו כאן',your_privacy:'הפרטיות שלכם',email_address:'כתובת דוא״ל',save_and_browse:'שמירה והתחלה',continue_visit:'המשך הביקור',search_event:'חיפוש באירוע',search:'חיפוש',reopen_favourites:'פתיחת המועדפים',basket_checkout:'סל ותשלום',event_folders:'תיקיות האירוע',end_session:'סיום הפעלה',your_basket:'הסל שלכם',total:'סה״כ',place_order:'ביצוע הזמנה'},
    hi:{language:'भाषा',choose_language:'भाषा चुनें',choose_your_language:'अपनी भाषा चुनें',currency_note:'सभी कीमतें पाउंड स्टर्लिंग (£) में रहेंगी।',browse_heading:'आप कैसे ब्राउज़ करना चाहेंगे?',just_browsing:'मैं सिर्फ़ देख रहा/रही हूँ',save_visit:'मेरी विज़िट सहेजें',continue_saved:'विज़िट पहले से सहेजी है? यहाँ जारी रखें',your_privacy:'आपकी गोपनीयता',email_address:'ईमेल पता',save_and_browse:'सहेजें और शुरू करें',continue_visit:'मेरी विज़िट जारी रखें',search_event:'इस इवेंट में खोजें',search:'खोजें',reopen_favourites:'पसंदीदा खोलें',basket_checkout:'बास्केट और चेकआउट',event_folders:'इवेंट फ़ोल्डर',end_session:'सत्र समाप्त करें',your_basket:'आपकी बास्केट',total:'कुल',place_order:'ऑर्डर करें'},
    bn:{language:'ভাষা',choose_language:'ভাষা নির্বাচন করুন',choose_your_language:'আপনার ভাষা নির্বাচন করুন',currency_note:'সব মূল্য পাউন্ড স্টার্লিং (£)-এ থাকবে।',browse_heading:'আপনি কীভাবে দেখতে চান?',just_browsing:'আমি শুধু দেখছি',save_visit:'আমার ভিজিট সংরক্ষণ করুন',continue_saved:'আগে ভিজিট সংরক্ষণ করেছেন? এখানে চালিয়ে যান',your_privacy:'আপনার গোপনীয়তা',email_address:'ইমেইল ঠিকানা',save_and_browse:'সংরক্ষণ করে শুরু করুন',continue_visit:'আমার ভিজিট চালিয়ে যান',search_event:'এই ইভেন্টে খুঁজুন',search:'খুঁজুন',reopen_favourites:'পছন্দের ছবি খুলুন',basket_checkout:'বাস্কেট ও পেমেন্ট',event_folders:'ইভেন্ট ফোল্ডার',end_session:'সেশন শেষ করুন',your_basket:'আপনার বাস্কেট',total:'মোট',place_order:'অর্ডার করুন'},
    ur:{language:'زبان',choose_language:'زبان منتخب کریں',choose_your_language:'اپنی زبان منتخب کریں',currency_note:'تمام قیمتیں پاؤنڈ اسٹرلنگ (£) میں رہیں گی۔',browse_heading:'آپ کس طرح براؤز کرنا چاہتے ہیں؟',just_browsing:'میں صرف دیکھ رہا/رہی ہوں',save_visit:'میرا وزٹ محفوظ کریں',continue_saved:'وزٹ پہلے محفوظ کیا ہے؟ یہاں جاری رکھیں',your_privacy:'آپ کی رازداری',email_address:'ای میل پتہ',save_and_browse:'محفوظ کریں اور شروع کریں',continue_visit:'میرا وزٹ جاری رکھیں',search_event:'اس ایونٹ میں تلاش کریں',search:'تلاش',reopen_favourites:'پسندیدہ کھولیں',basket_checkout:'باسکٹ اور ادائیگی',event_folders:'ایونٹ فولڈرز',end_session:'سیشن ختم کریں',your_basket:'آپ کی باسکٹ',total:'کل',place_order:'آرڈر دیں'},
    'zh-CN':{language:'语言',choose_language:'选择语言',choose_your_language:'请选择语言',currency_note:'所有价格均以英镑（£）显示。',browse_heading:'您想如何浏览？',just_browsing:'我只是浏览',save_visit:'保存我的访问',continue_saved:'已经保存过访问？在此继续',your_privacy:'您的隐私',email_address:'电子邮箱地址',save_and_browse:'保存并开始浏览',continue_visit:'继续我的访问',search_event:'搜索此活动',search:'搜索',reopen_favourites:'打开我的收藏',basket_checkout:'查看购物篮并结账',event_folders:'活动文件夹',end_session:'结束会话',your_basket:'您的购物篮',total:'总计',place_order:'提交订单'},
    'zh-TW':{language:'語言',choose_language:'選擇語言',choose_your_language:'請選擇語言',currency_note:'所有價格均以英鎊（£）顯示。',browse_heading:'您想如何瀏覽？',just_browsing:'我只是瀏覽',save_visit:'儲存我的造訪',continue_saved:'已儲存造訪？在此繼續',your_privacy:'您的隱私',email_address:'電子郵件地址',save_and_browse:'儲存並開始瀏覽',continue_visit:'繼續我的造訪',search_event:'搜尋此活動',search:'搜尋',reopen_favourites:'開啟我的最愛',basket_checkout:'購物籃與結帳',event_folders:'活動資料夾',end_session:'結束工作階段',your_basket:'您的購物籃',total:'總計',place_order:'送出訂單'},
    ja:{language:'言語',choose_language:'言語を選択',choose_your_language:'言語を選んでください',currency_note:'すべての価格は英ポンド（£）で表示されます。',browse_heading:'どのように閲覧しますか？',just_browsing:'見るだけです',save_visit:'訪問を保存',continue_saved:'保存済みの訪問がありますか？こちらから続ける',your_privacy:'プライバシー',email_address:'メールアドレス',save_and_browse:'保存して閲覧を開始',continue_visit:'訪問を続ける',search_event:'このイベントを検索',search:'検索',reopen_favourites:'お気に入りを開く',basket_checkout:'バスケットとお会計',event_folders:'イベントフォルダー',end_session:'セッションを終了',your_basket:'バスケット',total:'合計',place_order:'注文する'},
    ko:{language:'언어',choose_language:'언어 선택',choose_your_language:'언어를 선택하세요',currency_note:'모든 가격은 영국 파운드(£)로 표시됩니다.',browse_heading:'어떻게 둘러보시겠어요?',just_browsing:'그냥 둘러볼게요',save_visit:'방문 저장',continue_saved:'저장한 방문이 있나요? 여기서 계속하세요',your_privacy:'개인정보 보호',email_address:'이메일 주소',save_and_browse:'저장하고 시작',continue_visit:'방문 계속하기',search_event:'이 이벤트 검색',search:'검색',reopen_favourites:'즐겨찾기 열기',basket_checkout:'장바구니 및 결제',event_folders:'이벤트 폴더',end_session:'세션 종료',your_basket:'장바구니',total:'합계',place_order:'주문하기'},
    th:{language:'ภาษา',choose_language:'เลือกภาษา',choose_your_language:'เลือกภาษาของคุณ',currency_note:'ราคาทั้งหมดยังคงเป็นปอนด์สเตอร์ลิง (£)',browse_heading:'คุณต้องการเลือกดูอย่างไร?',just_browsing:'ฉันแค่เลือกดู',save_visit:'บันทึกการเข้าชม',continue_saved:'เคยบันทึกการเข้าชมแล้ว? ดำเนินการต่อที่นี่',your_privacy:'ความเป็นส่วนตัวของคุณ',email_address:'ที่อยู่อีเมล',save_and_browse:'บันทึกและเริ่ม',continue_visit:'ดำเนินการเข้าชมต่อ',search_event:'ค้นหาในงานนี้',search:'ค้นหา',reopen_favourites:'เปิดรายการโปรด',basket_checkout:'ตะกร้าและชำระเงิน',event_folders:'โฟลเดอร์งาน',end_session:'จบเซสชัน',your_basket:'ตะกร้าของคุณ',total:'รวม',place_order:'สั่งซื้อ'},
    vi:{language:'Ngôn ngữ',choose_language:'CHỌN NGÔN NGỮ',choose_your_language:'Chọn ngôn ngữ của bạn',currency_note:'Tất cả giá vẫn được hiển thị bằng bảng Anh (£).',browse_heading:'Bạn muốn xem theo cách nào?',just_browsing:'Tôi chỉ xem thôi',save_visit:'Lưu lượt xem của tôi',continue_saved:'Đã lưu lượt xem? Tiếp tục tại đây',your_privacy:'Quyền riêng tư của bạn',email_address:'Địa chỉ email',save_and_browse:'Lưu và bắt đầu',continue_visit:'Tiếp tục lượt xem',search_event:'Tìm kiếm trong sự kiện',search:'Tìm kiếm',reopen_favourites:'Mở mục yêu thích',basket_checkout:'Giỏ hàng và thanh toán',event_folders:'Thư mục sự kiện',end_session:'Kết thúc phiên',your_basket:'Giỏ hàng của bạn',total:'Tổng cộng',place_order:'Đặt hàng'},
    id:{language:'Bahasa',choose_language:'PILIH BAHASA',choose_your_language:'Pilih bahasa Anda',currency_note:'Semua harga tetap dalam pound sterling (£).',browse_heading:'Bagaimana Anda ingin melihat?',just_browsing:'Saya hanya melihat-lihat',save_visit:'Simpan kunjungan saya',continue_saved:'Sudah menyimpan kunjungan? Lanjutkan di sini',your_privacy:'Privasi Anda',email_address:'Alamat email',save_and_browse:'Simpan dan mulai',continue_visit:'Lanjutkan kunjungan',search_event:'Cari dalam acara ini',search:'Cari',reopen_favourites:'Buka favorit',basket_checkout:'Keranjang dan pembayaran',event_folders:'Folder acara',end_session:'Akhiri sesi',your_basket:'Keranjang Anda',total:'Total',place_order:'Buat pesanan'},
    ms:{language:'Bahasa',choose_language:'PILIH BAHASA',choose_your_language:'Pilih bahasa anda',currency_note:'Semua harga kekal dalam pound sterling (£).',browse_heading:'Bagaimana anda mahu melihat?',just_browsing:'Saya hanya melihat-lihat',save_visit:'Simpan lawatan saya',continue_saved:'Sudah menyimpan lawatan? Teruskan di sini',your_privacy:'Privasi anda',email_address:'Alamat e-mel',save_and_browse:'Simpan dan mula',continue_visit:'Teruskan lawatan',search_event:'Cari dalam acara ini',search:'Cari',reopen_favourites:'Buka kegemaran',basket_checkout:'Bakul dan pembayaran',event_folders:'Folder acara',end_session:'Tamatkan sesi',your_basket:'Bakul anda',total:'Jumlah',place_order:'Buat pesanan'},
    fil:{language:'Wika',choose_language:'PUMILI NG WIKA',choose_your_language:'Piliin ang iyong wika',currency_note:'Lahat ng presyo ay mananatili sa pounds sterling (£).',browse_heading:'Paano mo gustong tumingin?',just_browsing:'Titingin lang ako',save_visit:'I-save ang pagbisita ko',continue_saved:'May na-save na pagbisita? Magpatuloy dito',your_privacy:'Ang iyong privacy',email_address:'Email address',save_and_browse:'I-save at magsimula',continue_visit:'Ipagpatuloy ang pagbisita',search_event:'Maghanap sa event na ito',search:'Maghanap',reopen_favourites:'Buksan ang mga paborito',basket_checkout:'Basket at checkout',event_folders:'Mga folder ng event',end_session:'Tapusin ang session',your_basket:'Iyong basket',total:'Kabuuan',place_order:'Mag-order'}
  });

  let current = localStorage.getItem('pirouette_language');
  if (!current) {
    const browserLanguage = (navigator.language || 'en').replace('_','-');
    current = T[browserLanguage] ? browserLanguage : (T[browserLanguage.split('-')[0]] ? browserLanguage.split('-')[0] : 'en');
  }
  if (!T[current]) current='en';
  function text(key){ return (T[current] && T[current][key]) || en[key] || key; }
  function apply(){
    document.documentElement.lang=current;
    document.documentElement.dir=rtlLanguages.has(current)?'rtl':'ltr';
    document.body?.classList.toggle('rtl-language', rtlLanguages.has(current));
    document.querySelectorAll('[data-i18n]').forEach(el=>{ el.textContent=text(el.dataset.i18n); });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{ el.placeholder=text(el.dataset.i18nPlaceholder); });
    document.querySelectorAll('[data-i18n-aria]').forEach(el=>{ el.setAttribute('aria-label',text(el.dataset.i18nAria)); });
    document.querySelectorAll('[data-language-option]').forEach(el=>el.classList.toggle('active',el.dataset.languageOption===current));
    window.dispatchEvent(new CustomEvent('pirouette:languagechange',{detail:{language:current}}));
  }
  const dialog=document.getElementById('language-dialog');
  const grid=document.querySelector('[data-language-grid]');
  if(grid){
    languages.forEach(([code,label])=>{ const b=document.createElement('button'); b.type='button'; b.className='language-option'; b.dataset.languageOption=code; b.textContent=label; b.addEventListener('click',()=>{current=code;localStorage.setItem('pirouette_language',code);apply();dialog?.close();});grid.appendChild(b); });
  }
  document.querySelector('[data-language-button]')?.addEventListener('click',()=>dialog?.showModal());
  document.querySelector('[data-language-close]')?.addEventListener('click',()=>dialog?.close());
  dialog?.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
  apply();
})();
